USE [CryptoBay]
GO

ALTER TABLE [dbo].[Trace_12122018_1] DROP CONSTRAINT PK__Trace_12__AAAC09D83A1E2D8F;
GO

ALTER TABLE [dbo].[Trace_12122018_1] ADD PRIMARY KEY CLUSTERED 
(
	[RowNumber] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [TRACES]
GO